In [1]:
import pandas as pd

In [3]:
airbnb = pd.read_csv('listings.csv')
airbnb

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,NaN,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.90289,-87.68182,Entire home/apt,60,2,384,2020-03-08,2.81,1,321
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,NaN,Lincoln Park,41.91769,-87.63788,Entire home/apt,65,4,49,2019-10-23,0.63,9,300
4,10610,3 Comforts of Cooperative Living,2140,Lois,NaN,Hyde Park,41.79612,-87.59261,Private room,21,1,44,2020-02-14,0.61,5,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6392,45514091,Best view of Chicago downtown + optional parking,367907062,Melanie And Ryan,NaN,Near South Side,41.85574,-87.62507,Entire home/apt,146,2,0,NaN,NaN,4,180
6393,45514389,Luxurious 3Br/2Ba with optional parking and View,367907062,Melanie And Ryan,NaN,Near South Side,41.85561,-87.62342,Entire home/apt,195,2,0,NaN,NaN,4,180
6394,45514632,Two story Penthouse w private Rooftop & Great ...,367907062,Melanie And Ryan,NaN,Near South Side,41.85584,-87.62404,Entire home/apt,493,2,0,NaN,NaN,4,177
6395,45515281,West Town Private Room,347064639,Ali,NaN,West Town,41.89005,-87.66668,Private room,53,32,0,NaN,NaN,1,83
6396,45515581,Chicago Themed Private Garden Apartment,19541995,Kendal,NaN,Douglas,41.82964,-87.62048,Entire home/apt,61,1,0,NaN,NaN,1,170

In [6]:
df=airbnb.drop(['neighbourhood_group'], axis=1)

In [7]:
df

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,West Town,41.90289,-87.68182,Entire home/apt,60,2,384,2020-03-08,2.81,1,321
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,Lincoln Park,41.91769,-87.63788,Entire home/apt,65,4,49,2019-10-23,0.63,9,300
4,10610,3 Comforts of Cooperative Living,2140,Lois,Hyde Park,41.79612,-87.59261,Private room,21,1,44,2020-02-14,0.61,5,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6392,45514091,Best view of Chicago downtown + optional parking,367907062,Melanie And Ryan,Near South Side,41.85574,-87.62507,Entire home/apt,146,2,0,NaN,NaN,4,180
6393,45514389,Luxurious 3Br/2Ba with optional parking and View,367907062,Melanie And Ryan,Near South Side,41.85561,-87.62342,Entire home/apt,195,2,0,NaN,NaN,4,180
6394,45514632,Two story Penthouse w private Rooftop & Great ...,367907062,Melanie And Ryan,Near South Side,41.85584,-87.62404,Entire home/apt,493,2,0,NaN,NaN,4,177
6395,45515281,West Town Private Room,347064639,Ali,West Town,41.89005,-87.66668,Private room,53,32,0,NaN,NaN,1,83
6396,45515581,Chicago Themed Private Garden Apartment,19541995,Kendal,Douglas,41.82964,-87.62048,Entire home/apt,61,1,0,NaN,NaN,1,170